### ISSUE TITLE
typescript file rather than js file

### ISSUE THREAD

**Issue by ri8ika** [DamienP33/express-mongoose-generator#12]
I would like the code generated in .ts instead of .js.

How can I do that?

**Comment by DamienP33** [comment]
To generating code in TS, you must create the template in TS ;)

**Comment by ri8ika** [comment]
I am working on ts but this doesn't generate rather than js.

**Comment by ri8ika** [comment]
It would be helpful if you could show me steps for generating ts files.

**Comment by DamienP33** [comment]
The program is not intended to generate TS.
To make this possible, I need the templates in TS that will format the rendering.
There are 3 [templates](https://github.com/DamienP33/express-mongoose-generator/tree/master/templates), the controller, the model and the router.

I'll consider adding support for TS if more people are interested or if someone submits a PR

**Comment by hudsonburgess** [comment]
+1 -- I used this for a project that's now being migrated to TS; would be great to have that option available.
Seems like it would be simple to change... I might give it a shot this week.

**Comment by DamienP33** [comment]
I added the option for TS generation ( --ts ).
@hudsonburgess Can you test the correct rendering of TS files ?

**Comment by tiberiumihai** [comment]
I've checked the ts generation. Seems to be fine with 2 minor issues.

One in routes:
`import * as carController from './carController.ts';`
should be generated to 
`import carController from './carController.ts';`

Another one: importing from a ts file doesn't require the extension file name .ts in the import.
`import * as carController from './carController.ts';`
should be generated to 
`import carController from './carController';`


Is it possible to get it published also in npm after this fix?
Thanks for the hard work!

**Comment by abks90** [comment]
Fixed issues from @tiberiumihai #19

**Comment by DamienP33** [comment]
thanks for your contribution !
