### ISSUE TITLE
Output mixes tabs and spaces.

### ISSUE THREAD

**Issue by lukeocodes** [DamienP33/express-mongoose-generator#18]
It's something small really. I'm raising as an issue for myself to come back PR as soon as I have a moment.

👾

**Comment by DamienP33** [comment]
Can you describe the idea ?

**Comment by lukeoliff** [comment]
Currently the output of the generator mixes tabs and spaces. I'm going to modify it to standardise 2-space tabbing.

**Comment by DamienP33** [comment]
Normally, the entire project is standardized with : 
indent_style = space
indent_size = 4
