### ISSUE TITLE
Use the ObjectID type field

### ISSUE THREAD

**Issue by romuloctba** [DamienP33/express-mongoose-generator#2]
Hi @DamienP33 , thank you very much for this generator, it's been very helpfull.

I miss the ObjectID type, and hacked a bit into your code to provide this functions

I got it working for some time now, but today I share with you

Hope you like and it can be usefull or at least consider using this

I have no tests written thou, sorry

Here's the PR
https://github.com/DamienP33/express-mongoose-generator/pull/1

**Comment by DamienP33** [comment]
Hi @romuloctba ,
Thanks for your contribution !
I'm currently holiday, I will look your PullRequest soon ;)

**Comment by romuloctba** [comment]
@DamienP33  thank you so much :D I'm happy you are still arround. Please let me know if the code needs any adjustments. As I told you, my repo is already very different from this, cause of the folder structure,  and the commited part is the one needed to implement ObjectId field type :)

Again, I'd like to say this gen is thebest I found (btw, using fs.loadSync + .toString + .replace() for templating is awesome!) and it's been very usefull.

**Comment by DamienP33** [comment]
@romuloctba your contribution is still current ?

**Comment by romuloctba** [comment]
Yeah, sorry, I have to make the adjustments you asked

**Comment by DamienP33** [comment]
I can quickly integrate your changes and you note contributor, if you want

**Comment by DamienP33** [comment]
I added the changes and I added you as contributor.
Let me know if you change.

**Comment by ericwang1902** [comment]
very small but useful generator!
