### ISSUE TITLE
mongoose.connect() ???

### ISSUE THREAD

**Issue by kt-test** [DamienP33/express-mongoose-generator#3]
Hi, thank you very much for this nice stuff.
Can u plz tell me where can i put this (beginner :-) ) ? Can you integrate this in the generator?

**Comment by DamienP33** [comment]
Hi,
There are not obligation, I create a folder **config** with a db config file.
```javascript
module.exports = {
    uri:  process.env.OPENSHIFT_MONGODB_DB_URL || 'mongodb://localhost/my-db'
};
```
And make connection in www : 
```javascript
/**
 * Initialize MongoDB
 */
var mongoose = require('mongoose');
var dbCfg = require('../config/db');
mongoose.connect(dbCfg.uri);
```

**Comment by kt-test** [comment]
thanks a lot dude
