### ISSUE TITLE
Nested Document

### ISSUE THREAD

**Issue by djchrispurple** [DamienP33/express-mongoose-generator#6]
possibility to add nested sub document within the model?
thanks in advance

**Comment by DamienP33** [comment]
That is to say ?
Currently, it is possible to refer to a document with the ObjectId type.

```
var parentSchema = new Schema({ name: String });

var childSchema = new Schema({
  parent : {
	 	type: Schema.Types.ObjectId,
	 	ref: 'Parent'
	}
})
```

**Comment by djchrispurple** [comment]
Hi Damien,
how can we proceed the generator with 
{
   _id: objectId,
   name: string,
   addresses: [
                {
                  street: string,
                  city: string,
                  state: string,
                  zip: string
                },
              ]
 }
