### ISSUE TITLE
ALLOWER_FIELDS_TYPES  or ALLOWED_FIELDS_TYPES?

### ISSUE THREAD

**Issue by criduvero** [DamienP33/express-mongoose-generator#9]
I suppose  you have a typing error. You used "ALLOWER_FIELDS_TYPES" to replace "allowedFieldsTypes" in bin/mongoose-gen.

I think you should have used "ALLOWED_FIELDS_TYPES" instead of "ALLOWER_FIELDS_TYPES".

Let me know if I'm wrong. 

Good job. Thank you very much,Hug from Colombia

**Comment by DamienP33** [comment]
Exactly it is a typing error, i fixed it ;)
Thanks for your remark
